site_name: "PyBots - A library for quickly building simple robots"
repo_url: https://github.com/dhondta/pybots
site_author: dhondta
docs_dir: doc
pages:
  - Introduction: index.md
  - Features: features.md
  - Using Bots: usage.md
  - Creating Bots: create.md
  - Examples:
    - 'Hacky Easter 2017': examples/hacky-easter-2017.md
    - 'Hackvent 2017': examples/hackvent-2017.md
    - 'RingZer0': examples/ringzer0.md
    - 'Root-Me': examples/rootme.md
extra:
  mailto: alexandre.dhondt@gmail.com
theme: readthedocs
use_directory_urls: false
markdown_extensions:
  - admonition
  - codehilite:
      linenums: true
